// Generated Hotspot Configuration
// Auto-generated by MetaRoom3D — merges every floor exported into this folder.
// Do not hand-edit; re-exporting a floor's GLB regenerates this file from
// .hotspot-cache.json (also in this folder), which is what actually gets merged.

export const hotspotData = [
  {
    theta: 1.5497,
    phi: 1.8076,
    radius: 480,
    color: 0xff6600,
    name: 'Foyer',
    panoramaImage: 'panos/Foyer.jpg',
    fromRoom: 'Dining-Room'
  },
  {
    theta: -0.5665,
    phi: 1.7260,
    radius: 480,
    color: 0xff6600,
    name: 'Dining-Room',
    panoramaImage: 'panos/Dining-Room.jpg',
    fromRoom: 'Foyer'
  },
  {
    theta: 2.2614,
    phi: 1.7532,
    radius: 480,
    color: 0xff6600,
    name: 'Landing',
    panoramaImage: 'panos/Landing.jpg',
    fromRoom: 'Foyer'
  },
  {
    theta: 3.0526,
    phi: 1.8621,
    radius: 480,
    color: 0xff6600,
    name: 'Landing-2',
    panoramaImage: 'panos/Landing-2.jpg',
    fromRoom: 'Landing'
  },
  {
    theta: 1.4561,
    phi: 1.8022,
    radius: 480,
    color: 0xff6600,
    name: 'Foyer',
    panoramaImage: 'panos/Foyer.jpg',
    fromRoom: 'Landing'
  },
  {
    theta: 0.3385,
    phi: 1.6398,
    radius: 480,
    color: 0xff6600,
    name: 'Landing',
    panoramaImage: 'panos/Landing.jpg',
    fromRoom: 'Landing-2'
  }
];

export const roomConnections = {
  'Dining-Room': ['Foyer'],
  'Foyer': ['Dining-Room', 'Landing'],
  'Landing': ['Foyer', 'Landing-2'],
  'Landing-2': ['Landing']
};

export const availablePanoramas = [
  'panos/Dining-Room.jpg',
  'panos/Foyer.jpg',
  'panos/Landing-2.jpg',
  'panos/Landing.jpg'
];

export const modelToPanoramaMapping = [
  {
    nodeNamePatterns: ['dining-room'],
    fallbackIndex: 0,
    panoramaImage: 'panos/Dining-Room.jpg',
    displayName: 'Dining-Room'
  },
  {
    nodeNamePatterns: ['foyer'],
    fallbackIndex: 1,
    panoramaImage: 'panos/Foyer.jpg',
    displayName: 'Foyer'
  },
  {
    nodeNamePatterns: ['landing'],
    fallbackIndex: 3,
    panoramaImage: 'panos/Landing.jpg',
    displayName: 'Landing'
  },
  {
    nodeNamePatterns: ['landing-2'],
    fallbackIndex: 2,
    panoramaImage: 'panos/Landing-2.jpg',
    displayName: 'Landing-2'
  }
];
